const ExcelExportData = [
  {
    email: "abeera@lms.com",
    first_name: "Abeera",
    last_name: "Arshad",
    gender: "F",
    city: "Karachi",
    country: "Pakistan",
    password: "abeera",
    phone_number: "03162587945",
    is_active: true,
    role: "instructor",
  },
  {
    email: "samara@lms.com",
    first_name: "Samara",
    last_name: "Mohsin",
    gender: "F",
    city: "karachi",
    password: "samara",
    country: "Pakistan",
    phone_number: "03165879468",
    is_active: true,
    role: "instructor",
  },
  {
    email: "mohsen@lms.com",
    first_name: "Mohsen",
    last_name: "Ali",
    gender: "M",
    city: "Turbat",
    password: "mohsen",
    country: "Pakistan",
    phone_number: "03162477395",
    is_active: true,
    role: "learner",
  },
  {
    email: "mufaddal@lms.com",
    first_name: "Mufaddal",
    last_name: "Mustafa",
    gender: "M",
    city: "Karachi",
    country: "Pakistan",
    password: "mufaddal",
    phone_number: "03369874582",
    is_active: true,
    role: "learner",
  },
  {
    email: "samra@lms.com",
    first_name: "Samra",
    last_name: "Almas",
    gender: "F",
    city: "Karachi",
    password: "samra",
    country: "Pakistan",
    phone_number: "03162548556",
    is_active: true,
    role: "admin",
  },
  {
    email: "nabeel@lms.com",
    first_name: "Nabeel",
    last_name: "Ahmed",
    gender: "M",
    city: "Karachi",
    password: "nabeel",
    country: "Pakistan",
    phone_number: "035897787877",
    is_active: true,
    role: "learner",
  },
  {
    email: "hassan@lms.com",
    first_name: "Hassan",
    last_name: "Ali",
    gender: "M",
    city: "Karachi",
    password: "hassan",
    country: "Pakistan",
    phone_number: "0316987546",
    is_active: true,
    role: "learner",
  },
  {
    email: "zia@lms.com",
    first_name: "Zia",
    last_name: "Rasheed",
    gender: "M",
    city: "Karachi",
    country: "Pakistan",
    password: "zia",
    phone_number: "03369874576",
    is_active: true,
    role: "learner",
  },
  {
    email: "muddasir@lms.com",
    first_name: "Muddasir",
    last_name: "Raza",
    gender: "M",
    city: "karachi",
    password: "muddasir",
    country: "Pakistan",
    phone_number: "031625879745",
    is_active: true,
    role: "learner",
  },
  {
    email: "hasan@lms.com",
    first_name: "Muhammad",
    last_name: "Hasan",
    gender: "M",
    city: "Karachi",
    country: "Pakistan",
    password: "hasan",
    phone_number: "0332587977",
    is_active: false,
    role: "learner",
  },
  {
    email: "aiman@lms.com",
    first_name: "Aiman",
    last_name: "Zaheer",
    gender: "F",
    city: "Karachi",
    country: "Pakistan",
    password: "aiman",
    phone_number: "0332577895",
    is_active: false,
    role: "learner",
  },
  {
    email: "mohsen@work.com",
    first_name: "Mohsen",
    last_name: "Ali",
    gender: "M",
    city: "Turbat",
    country: "Pak",
    password: "mohsen",
    phone_number: "03162485944",
    is_active: false,
    role: "instructor",
  },
  {
    id: 39,
    username: null,
    email: "waqar@work.com",
    first_name: "Muhammad",
    last_name: "Waqar",
    gender: "M",
    city: "Karachi",
    country: "Pak",
    password: "waqar",
    phone_number: "03162485944",
    is_active: false,
    role: "learner",
  },
  {
    email: "mufaddal@work.com",
    first_name: "Mufaddal",
    last_name: "Mustafa",
    gender: "M",
    city: "Karachi",
    country: "Pak",
    password: "mufaddal",
    phone_number: "03162485944",
    is_active: false,
    role: "learner",
  },
  {
    email: "samra@work.com",
    first_name: "Samra",
    last_name: "Almas",
    gender: "F",
    city: "Karachi",
    country: "Pak",
    password: "samra",
    phone_number: "03162485944",
    is_active: false,
    role: "learner",
  },
  {
    email: "abeera@work.com",
    first_name: "Abeera",
    last_name: "Arshad",
    gender: "F",
    city: "Karachi",
    country: "Pak",
    password: "abeera",
    phone_number: "03162485944",
    is_active: false,
    role: "learner",
  },
  {
    email: "sam@work.com",
    first_name: "Sam",
    last_name: "Javed",
    gender: "F",
    city: "Karachi",
    country: "Pak",
    password: "sam",
    phone_number: "03162485944",
    is_active: false,
    role: "learner",
  },
  {
    email: "mohsenali3366@gmail.com",
    first_name: "Mohsen",
    last_name: "Javed",
    gender: "M",
    city: "Karachi",
    country: "Pak",
    password: "mohsen",
    phone_number: "03162485944",
    is_active: false,
    role: "learner",
  },
];
export default ExcelExportData;
